spring:
  datasource:
    url: ${datasource.url:NONE}
    username: ${datasource.username:NONE}
    password: ${datasource.password:NONE}
    driver-class-name: com.mysql.cj.jdbc.Driver
  profiles:
    include: oauth
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
  session:
    store-type: redis
  redis:
    host: localhost
    port: 6379
